/*
 * UPI Account Management API
 * API for managing UPI Account in the NPCI Family
 *
 * OpenAPI spec version: 2.0
 * Contact: rohith.gola@npci.org.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Account;
import io.swagger.client.model.AccountsListResponse;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for UpiControllerApi
 */
@Ignore
public class UpiControllerApiTest {

    private final UpiControllerApi api = new UpiControllerApi();

    /**
     * Create Account
     *
     * Create Account
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createAccountTest() throws Exception {
        Account body = null;
        String response = api.createAccount(body);

        // TODO: test validations
    }
    /**
     * Delete Account by Email
     *
     * Delete complete account details using the email ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAccountTest() throws Exception {
        String e = null;
        String response = api.deleteAccount(e);

        // TODO: test validations
    }
    /**
     * Edit account details by email
     *
     * Edit account details using the email ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void editAccountTest() throws Exception {
        Account body = null;
        String e = null;
        String response = api.editAccount(body, e);

        // TODO: test validations
    }
    /**
     * Get account details by email
     *
     * Fetches complete account details using the email ID
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void viewAccountTest() throws Exception {
        String e = null;
        String response = api.viewAccount(e);

        // TODO: test validations
    }
    /**
     * Get all account details
     *
     * Fetches complete account details
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void viewAllAccountTest() throws Exception {
        AccountsListResponse response = api.viewAllAccount();

        // TODO: test validations
    }
}
