/*
 * UPI Account Management API
 * API for managing UPI Account in the NPCI Family
 *
 * OpenAPI spec version: 2.0
 * Contact: rohith.gola@npci.org.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
